name: Update code docs

on:
  repository_dispatch:
    types: [code-update]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.JELLYROCK_BOT_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Checkout jellyrock
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: jellyrock/jellyrock
          path: jellyrock
          ref: main
      - name: Build code docs
        # TODO: fix jsdoc build errors then remove '|| true' from run command below
        run: npm run build || true
      - name: Commit any changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: Update code docs
          # use JellyRock-bot to commit the changes instead of the default github-actions[bot]
          commit_user_name: JellyRock-bot
          commit_user_email: c.ewert@gmail.com
          # use JellyRock-bot to author the changes instead of the default author of the merge commit
          commit_author: JellyRock-bot <c.ewert@gmail.com>
